---
- hosts: all
  tasks:
    - name: build dnsmasq
      docker_image:
          name: dnsmasq
          path: ./dnsmasq
          repository: localhost:5000/dnsmasq
          tag: v1
          push: yes

    - name: run dnsmasq
      docker_container:
        name: dnsmasq
        image: localhost:5000/dnsmasq:v1
        capabilities:
            - NET_ADMIN
        network_mode: host
        command: --address=/meguca.moe/192.168.0.100
        ports:
            - "53:53"
        volumes:
            - "./dnsmasq/conf:/etc/dnsmasq"
        restart_policy: always
