version: '3'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
    whoami:
        image: jwilder/whoami
        environment:
            - VIRTUAL_HOST=whoami.meguca.moe

    glances:
        image: nicolargo/glances
        #network_mode: host
        pid: host
        expose:
            - "61208"
        ports:
            - "61208:61208"
            - "61209:61209"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        environment:
            - VIRTUAL_HOST=nozoku.meguca.moe
            - VIRTUAL_PORT=61208
            - GLANCES_OPT=-w

    jenkins:
        build: ./blueocean
        expose:
            - "8080"
        volumes:
            - /var/lib/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - VIRTUAL_HOST=aoiumi.meguca.moe
            - VIRTUAL_PORT=8080
            - NETWORK_ACCESS=internal
            - HOME=/var/jenkins_home

    site:
        build: ./site
        user: "1000"
        expose:
            - "8008"
        volumes:
            - /var/www/meguca.moe:/data/site
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
        environment:
            - VIRTUAL_HOST=meguca.moe
            - VIRTUAL_PORT=8008

    scribl:
        image: localhost:5000/scribl
        depends_on: 
          - scribl_db
        command: rackup -p 3001 --host 0.0.0.0
        expose:
            - "3001"
        ports:
            - "3001:3001"
        environment:
            - VIRTUAL_HOST=scribl.meguca.moe
    scribl_db:
        image: postgres

