version: '3'
networks:
  misaka:
    external: true

services:
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        labels:
          - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /etc/nginx/htpasswd:/etc/nginx/htpasswd
            - /etc/nginx/certs:/etc/nginx/certs
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - ./files/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf
        networks:
          - misaka
        environment:
          - HTTPS_METHOD=noredirect

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion:latest
        container_name: letsencrypt
        restart: always
        depends_on:
            - nginx-proxy
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - /etc/nginx/htpasswd:/etc/nginx/htpasswd
          - /etc/nginx/certs:/etc/nginx/certs:rw
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - vhost:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
        networks:
          - misaka
        environment:
          - REUSE_PRIVATE_KEYS=true
          - DEFAULT_EMAIL=ipickering2@gmail.com
          - DEBUG=true

    whoami:
        image: jwilder/whoami
        environment:
            - VIRTUAL_HOST=whoami.nori.moe
            - LETSENCRYPT_HOST=whoami.nori.moe
        networks:
          - misaka

    glances:
        image: nicolargo/glances
        #network_mode: host
        pid: host
        expose:
            - "61208"
        ports:
            - "61208:61208"
            - "61209:61209"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        environment:
            - VIRTUAL_HOST=nozoku.nori.daikon
            - VIRTUAL_PORT=61208
            - NETWORK_ACCESS=internal
            - GLANCES_OPT=-w
        networks:
          - misaka

    shaarli:
      image: shaarli/shaarli
      volumes:
          - /mnt/hibiki/config/shaarli/cache:/var/www/shaarli/cache
          - /mnt/hibiki/config/shaarli/data:/var/www/shaarli/data
          - /mnt/hibiki/config/shaarli/tpl:/var/www/shaarli/tpl
      environment:
          - VIRTUAL_HOST=share.nori.moe
          - LETSENCRYPT_HOST=share.nori.moe
      networks:
        - misaka

    plex:
      image: plexinc/pms-docker
      #expose:
      #  - "32400"
      #ports:
      #  - "32400:32400"
      #  - "3005:3005"
      #  - "8324:8324"
      #  - "32469:32469"
      #  - "1900:1900"
      #  - "32410:32410"
      #  - "32412:32412"
      #  - "32413:32413"
      #  - "32414:32414"
      network_mode: host
      volumes:
        - /mnt/hibiki/config/plex/config:/config
        - /mnt/hibiki/config/plex/transcode:/transcode
        - /mnt/hibiki:/data
        - /var/run/docker.sock:/tmp/docker.sock:ro
      environment:
        #- HOSTNAME="plex"
        - TZ="America/Los_Angeles"
        #- ADVERTISE_IP="http://192.168.1.100:32400/"
        #- VIRTUAL_HOST=plex.nori.moe
        #- VIRTUAL_PORT=32400


              # jenkins:
              #     build: ./blueocean
              #     expose:
              #         - "8080"
              #     volumes:
              #         - /var/lib/jenkins:/var/jenkins_home
              #         - /var/run/docker.sock:/var/run/docker.sock
              #     environment:
              #         - VIRTUAL_HOST=aoiumi.nori.moe
              #         - VIRTUAL_PORT=8080
              #         - NETWORK_ACCESS=internal
              #         - HOME=/var/jenkins_home
              #
              # site:
              #     build: ./site
              #     user: "1000"
              #     expose:
              #         - "8008"
              #     volumes:
              #         - /var/www/nori.moe/md:/data/site/md
              #         - /etc/group:/etc/group:ro
              #         - /etc/passwd:/etc/passwd:ro
              #     environment:
              #         - VIRTUAL_HOST=nori.daikon
              #         - VIRTUAL_PORT=8008

              # scribl:
              #     build: ./scribl
              #     depends_on:
              #       - scribl_db
              #     command: rackup -p 3001 --host 0.0.0.0
              #     expose:
              #         - "3001"
              #     ports:
              #         - "3001:3001"
              #     environment:
              #         - VIRTUAL_HOST=scribl.nori.moe
              # scribl_db:
              #     image: postgres

    emby:
      image: emby/embyserver
      ports:
          - "8096:8096"
      networks:
          - misaka
      volumes:
          - /mnt/hibiki/config/emby:/config
          - /mnt/hibiki/video:/mnt/share
          - /mnt/hibiki/voice:/mnt/share2
      environment:
        - VIRTUAL_HOST=emby.nori.daikon
        - VIRTUAL_PORT=8096
        - UID=1000
        - GID=1000

    html-server:
      image: localhost:5000/html-server:v1
      ports:
          - "800:80"
      networks:
          - misaka
      environment:
        - VIRTUAL_HOST=nori.moe
        - VIRTUAL_PORT=80
        - UID=1000
        - GID=1000

    wiki:
      image: bitnami/dokuwiki
      ports:
          - "5001:80"
          - "5002:443"
      networks:
          - misaka
      volumes:
          - /mnt/hibiki/config/dokuwiki:/bitnami
      environment:
        - VIRTUAL_HOST=wiki.nori.moe
        - VIRTUAL_PORT=80
        - LETSENCRYPT_HOST=wiki.nori.moe
        - UID=1000
        - GID=1000

    lanraragi:
      image: difegue/lanraragi
      ports:
          - "3000:3000"
      networks:
          - misaka
      volumes:
          - /mnt/hibiki/araragi:/home/koyomi/lanraragi/content
      environment:
        - VIRTUAL_HOST=araragi.nori.daikon
        - VIRTUAL_PORT=3000
        - LRR_UID=1000
        - LRR_GID=1000

    elona-js:
      image: localhost:5000/elona-js:v1
      networks:
          - misaka
      environment:
        - VIRTUAL_HOST=elonajs.nori.moe
        - VIRTUAL_PORT=80
        - LETSENCRYPT_HOST=elonajs.nori.moe
        - UID=1000
        - GID=1000

    synapse:
      image: localhost:5000/synapse
      networks:
          - misaka
      environment:
        - UID=1000
        - GID=1000
          
volumes:
    vhost:
    html:
