---
- hosts: all
  tasks:
    - name: Install Jenkins
      import_role: 
          name: jenkins
      vars:
          install_jenkins: True
          jenkins_admin_password: jenkins
          jenkins_ssh_private_key: /var/lib/jenkins/jenkins-id_rsa
          jenkins_ssh_public_key: /var/lib/jenkins/jenkins-id_rsa.pub
          jenkins_git_user: git
          jenkins_git_host: github.com
          jenkins_git_path: git
          jenkins_git_repositories:
              - Ruin0x11/scribl
