---
- hosts: all
  vars:
      user: ruin
      resolv_nameservers:
          - 192.168.0.100
          - 8.8.8.8
          - 8.8.4.4
  roles:
      - resolv
  tasks:
      - name: install /var/www
        file:
            path: "{{ item }}"
            state: directory
            owner: "{{ user }}"
            group: "{{ user }}"
            recurse: yes
        with_items:
            - /var/www
            - /var/www/meguca.moe
      - name: create registry directory
        file: path=/var/lib/registry state=directory

      - name: raise docker-compose services
        docker_service:
            project_src: .

      - name: Configure jenkins
        import_role:
            name: jenkins
        vars:
            jenkins_admin_password: jenkins
            jenkins_ssh_private_key: /var/lib/jenkins/jenkins-id_rsa
            jenkins_ssh_public_key: /var/lib/jenkins/jenkins-id_rsa.pub
            jenkins_git_user: git
            jenkins_git_host: github.com
            jenkins_git_path: git
            jenkins_git_repositories:
                - Ruin0x11/scribl
